### ISSUE TITLE
nvim-cmp support

### ISSUE THREAD

**Issue by eloycoto** [codota/tabnine-nvim#6] opened 2022-12-15 21:11 UTC
Hi!

Do you have plans to support nvim-cmp? At the moment is a bit intrusive(Because of the LSP), and it will be good to have the support natively, I'm struggling with cmp-tabnine on multi-line, and official support will be great. 

The interface to add support is pretty easy, like:

```lua
local cmp = require('cmp')

local Source = {
}

function Source.new()
  last_instance = setmetatable({}, { __index = Source })
  last_instance:on_exit(0)
  return last_instance
end

function Source.is_available(self)
  return true
end

function Source.get_debug_name()
  return 'TabNine'
end


function Source.complete(self, ctx, callback)
  local input = string.sub(ctx.context.cursor_before_line, ctx.offset - 1)
  local prefix = string.sub(ctx.context.cursor_before_line, 1, ctx.offset - 1)

  local items = {}
  ---  Do tabnine magic here
  table.insert(items, {
    filterText = "TabNine magic here"
    label = "TabNine magic here",
    textEdit = {
      newText = "Tabnine magic here" ,
      range = {
        start = {
          line = ctx.context.cursor.row - 1,
          character = ctx.context.cursor.col - 1 - #input,
        },
        ['end'] = {
          line = ctx.context.cursor.row - 1,
          character = ctx.context.cursor.col - 1,
        },
      },
    },
  })


  callback({
    items = items,
    isIncomplete = true,
  })
end

cmp.register_source('cmp_tabnine', M.tabnine_source)
```

Here is an example video:
https://www.youtube.com/watch?v=gAsYolNrjtQ

And the code:
https://github.com/wincent/wincent/blob/91ebe56f414748078c93d011f5774553bddf3537/aspects/nvim/files/.config/nvim/lua/wincent/cmp/handles.lua

My idea is to have nvim with tabnine and LSP playing nice :-) 

Happy to do contribution in a branch, and beta-testing :-)

**Comment by amirbilu** [comment] 2022-12-17 20:43
Hi @eloycoto 
Thanks for reaching out!
I'll definitely take a look into this

**Comment by amirbilu** [comment] 2022-12-18 07:28
@eloycoto what would be the expected behavior in your opinion? 
Tabnine completions are inline (virtual text) - This definitely better experience with multi-line suggestions.

**Comment by eloycoto** [comment] 2022-12-18 11:00
@amirbilu with ghost text multiline is supported, no? Maybe @hrsh7th can provide some insights here. 

https://github.com/hrsh7th/nvim-cmp/blob/10b1d11252cb106ab7416a51167e4e9af3f05598/doc/cmp.txt#L648

My ideal thing will be:

CMP by default, with tabnine enabled in there. like cmp-tabnine project. But getting inside current LSP is also super helpful. 
On keymap, being able to use the current behaviour, like C^scape just give me an idea about what I need.

**Comment by amirbilu** [comment] 2022-12-18 16:51
@eloycoto with cmp ghost text you still get the whole completion popup experience which is not optimal for multiline suggestions.

If you like short suggestions in the completion popup.. you  can work with both plugins together

**Comment by arjes** [comment] 2022-12-21 03:43
Just want to chime in to say that I would like to see this plugin provide a source from cmp too.

I do not want to use the  provided virtual text because this plugin is fighting nvim-cmp over the virtual text content.

Take a look at how https://github.com/zbirenbaum/copilot-cmp integrates multi-line suggestions into the details text

**Comment by hrsh7th** [comment] 2022-12-21 05:27
Hm... I don't use tabnine/copilot as a completion source for now.
(I think ghost text like appearance is best solution for those plugins)

**Comment by eloycoto** [comment] 2022-12-21 11:26
@arjes +1, I'm using as it is, and It's totally unusable with both plugins :(

**Comment by amirbilu** [comment] 2022-12-21 12:06
@eloycoto, @arjes I can add the option to not trigger Tabnine completions while the popup menu is visible - how does that sound?

**Comment by eloycoto** [comment] 2022-12-21 12:11
@amirbilu great idea for me, Tabnine completations of, and cmp-support inside it! That will be the best thing for me.  Something like this:

```
require('tabnine').setup({
  disable_auto_comment=true,
  accept_keymap=nil,
  disable_suggestion=true,
  debounce_ms = 300,
  suggestion_color = {gui = "#808080", cterm = 244},
  plugins = {
    cmp= true
  }
})
```

That for me will be great :-)

**Comment by arjes** [comment] 2022-12-21 13:23
@hrsh7th I 100% agree with you that ghost text is the best solution for one of the biggest selling points of this plugin, but that case it just the selling point. It isn't the 99.5% usecase. 

The usecase where ghost text completion shines is where it is filling out large portions of the functions/methods _before_ I have started typing.

Once I start typing the ghost text is competing with my other completion sources which are likely more accurate (LSP).

So in my ideal usecase, I would want to see the ghost text provided by this plugin only when there is not a completion option otherwise being presented, once there are completion options I would _prefer_ to see it offer it's completions there so I can review them. If simply making them go away and relying on `cmp_tabnine` for the cmp integration is what is required then that will work.

**Comment by amirbilu** [comment] 2022-12-21 15:00
@arjes / @eloycoto let me know of what you think on this https://github.com/codota/tabnine-nvim/pull/7

**Comment by amirbilu** [comment] 2022-12-21 17:45
Merged :)
Anything else or can I close this ticket?

**Comment by eloycoto** [comment] 2022-12-21 19:49
Hi, 

Just to make it clear, the current status is the following:

- If you want all line suggestions, using `tabnine-nvim`
- As soon you get cmp working, you need to switch to cmp-tabnine. 

Am I correct?

**Comment by amirbilu** [comment] 2022-12-21 19:59
Use tabnine-nvim to get inline, whole line & full function completions.

If you want to still have short Tabnine suggestions in the popup menu.. you can leave cmp tabnine on

**Comment by eloycoto** [comment] 2022-12-22 06:12
Awesome, thanks!

**Closed** 2022-12-22 06:15 UTC

**Comment by tzachar** [comment] 2022-12-25 07:13
Author of cmp-tabnine here.
I don't understand why can't we get mutiline suggestions in cmp.
@amirbilu  Is tabnine actively prohibiting it? Is cmp-tabnine doing something wrong?

**Comment by amirbilu** [comment] 2022-12-25 07:26
Hi @tzachar 
Multiline suggestions are mostly triggered after newline. Is newline trigger character of `cmp` ?

**Comment by tzachar** [comment] 2022-12-25 07:31
You can set it up like it.
But you can also trigger completion manually, and still not get multiline suggestions.

**Comment by amirbilu** [comment] 2022-12-25 07:41
What is the `Autocomplete` requests sent by `cmp-tabnine `on this [line](https://github.com/codota/tabnine-nvim/blob/689336fcc2d2f79c346c590ad48c049f08bc8a4f/expamples/python.py#L2)?

**Comment by tzachar** [comment] 2022-12-25 07:42
@amirbilu 
I think I understand the problem now.
It looks like that when using the cloud, no `correlation_id` is returned, which seems like a backend bug.

Here is a sample request I am making:
```lua
{                                                                                                                                                                             
  request = {                                                                                                                                                                 
    Autocomplete = {                                                                                                                                                          
      after = "",                                                                                                                                                             
      before = "# calculate average of array\n",                                                                                                                              
      correlation_id = 54,                                                                                                                                                    
      filename = "/tmp/1.py",                                                                                                                                                 
      indentation_size = 4,                                                                                                                                                   
      max_num_results = 20,                                                                                                                                                   
      region_includes_beginning = true,                                                                                                                                       
      region_includes_end = false                                                                                                                                             
    }                                                                                                                                                                         
  },                                                                                                                                                                          
  version = "4.4.207"                                                                                                                                                         
}                             
```

and here is the reply:

```lua
{                                                                                                                                                                             
  docs = {},                                                                                                                                                                  
  is_locked = false,                                                                                                                                                          
  old_prefix = "",                                                                                                                                                            
  results = { {                                                                                                                                                               
      completion_kind = "Snippet",                                                                                                                                            
      detail = "0.000",                                                                                                                                                       
      is_cached = false,                                                                                                                                                      
      kind = 15,                                                                                                                                                              
      new_prefix = "\ndef average(array):\n    return sum(array)/len(array)",                                                                                                 
      new_suffix = "",                                                                                                                                                        
      old_suffix = "",                                                                                                                                                        
      origin = "CLOUD2"                                                                                                                                                       
    }, {                                                                                                                                                                      
      completion_kind = "Snippet",                                                                                                                                            
      detail = "0.000",                                                                                                                                                       
      is_cached = false,                                                                                                                                                      
      kind = 15,                                                                                                                                                              
      new_prefix = "\ndef average(array):\n    return sum(array)/len(array)",                                                                                                 
      new_suffix = "",                                                                                                                                                        
      old_suffix = "",                                                                                                                                                        
      origin = "CLOUD2"                                                                                                                                                       
    } },                                                                                                                                                                      
  snippet_context = {                                                                                                                                                         
    context_len = 29,                                                                                                                                                         
    first_token_score = "0.207",                                                                                                                                              
    generated_tokens = 60,                                                                                                                                                    
    intent_metadata = vim.NIL,                                                                                                                                                
    is_cached = false,                                                                                                                                                        
    resolved_dependencies = false,                                                                                                                                            
    response_time_ms = 1077,                                                                                                                                                  
    snippet_id = "07a82ca8-8085-4bd6-866e-cd12510df75d",                                                                                                                      
    stop_reason = "stop_token",                                                                                                                                               
    user_intent = "Comment"                                                                                                                                                   
  },                                                                                                                                                                          
  user_message = {}                                                                                                                                                           
}                                                                          
```

Can you please verify?

**Comment by tzachar** [comment] 2022-12-25 08:02
cmp-tabnine is reliant on the `correlation_id`. If I disable its usage, I can get multiline suggestions. However, I cannot apply this change in general, as it breaks the asynchronous assumptions made by cmp.

**Comment by amirbilu** [comment] 2022-12-25 08:59
@tzachar thanks.. checking this

**Comment by amirbilu** [comment] 2022-12-25 09:51
it's indeed an issue.. I'll try to push for a fix

**Comment by amirbilu** [comment] 2022-12-25 10:00
fix in master.. will be released on next push to GA (might take couple of days)

**Comment by tzachar** [comment] 2022-12-25 10:01
Cool. One this is fixed cmp-tabnine should have no problem supporting multiline mode.

**Comment by amirbilu** [comment] 2022-12-26 09:42
@tzachar can you check on beta now? 
Make sure you're on Tabnine `4.4.212`
![image](https://user-images.githubusercontent.com/7681048/209533346-37e9dea1-8761-4c68-925c-fcdbf1b9bba3.png)

**Comment by tzachar** [comment] 2022-12-26 11:29
running 4.4.212, still no correlation id:

```lua
{                                                                                                                                                                             
  docs = {},                                                                                                                                                                  
  is_locked = false,                                                                                                                                                          
  old_prefix = "",                                                                                                                                                            
  results = { {                                                                                                                                                               
      completion_kind = "Snippet",                                                                                                                                            
      detail = "0.000",                                                                                                                                                       
      is_cached = false,                                                                                                                                                      
      kind = 15,                                                                                                                                                              
      new_prefix = '\ndef sum_of_array(array):\n    sum = 0\n    for i in range(len(array)):\n        sum += array[i]\n    return sum\n"""',                                  
      new_suffix = "",                                                                                                                                                        
      old_suffix = "",                                                                                                                                                        
      origin = "CLOUD2"                                                                                                                                                       
    }, {                                                                                                                                                                      
      completion_kind = "Snippet",                                                                                                                                            
      detail = "0.000",                                                                                                                                                       
      is_cached = false,                                                                                                                                                      
      kind = 15,                                                                                                                                                              
      new_prefix = '\ndef sum_of_array(array):\n    sum = 0\n    for i in range(len(array)):\n        sum += array[i]\n    return sum\n"""',                                  
      new_suffix = "",                                                                                                                                                        
      old_suffix = "",                                                                                                                                                        
      origin = "CLOUD2"                                                                                                                                                       
    } },                                                                                                                                                                      
  snippet_context = {                                                                                                                                                         
    context_len = 24,                                                                                                                                                         
    first_token_score = "0.202",                                                                                                                                              
    generated_tokens = 60,                                                                                                                                                    
    intent_metadata = {                                                                                                                                                       
      current_line_indentation = 0,                                                                                                                                           
      previous_line_indentation = 0,                                                                                                                                          
      triggered_after_character = "y"                                                                                                                                         
    },                                                                                                                                                                        
    is_cached = false,                                                                                                                                                        
    resolved_dependencies = false,                                                                                                                                            
    response_time_ms = 1071,                                                                                                                                                  
    snippet_id = "49284411-20ee-42ea-bf5c-0b178d75f6b8",                                                                                                                      
    stop_reason = "stop_token",                                                                                                                                               
    user_intent = "Comment"                                                                                                                                                   
  },                                                                                                                                                                          
  user_message = {}                                                                                                                                                           
}                                                     
```

**Comment by amirbilu** [comment] 2022-12-26 14:11
@tzachar terribly sorry for the confusion - this is going to be released on the next push. Will you keep posted here.

**Comment by tzachar** [comment] 2022-12-26 14:16
Cool

**Comment by amirbilu** [comment] 2022-12-26 19:07
@tzachar check out version `4.4.213` - verified it has `correlation_id`

**Comment by tzachar** [comment] 2022-12-27 06:55
Checked it, and everything works now.
Thanks.
