### ISSUE TITLE
Can't use code action if tabnine plugin is used

### ISSUE THREAD

**Issue by MSMazaya** [codota/tabnine-nvim#65] opened 2023-04-20 01:28 UTC
Every time I turn on tabnine plugin, I can't get my LSP code action. It seems that the issue is happening to me on every language lsp that I use. My neovim config is available [here](https://github.com/MSMazaya/.dotfiles/tree/tabnine-issue/nvim/.config/nvim). Here I attach a video reproducing the bug for my dart and rust project by commenting the tabnine plugin and uncomment it. The result shows that when it is turned on, I got a message that says `No code actions available`. When i turn it off, the error goes away and the code action is working just fine.

https://user-images.githubusercontent.com/73002733/233234042-8a9aed9b-f26f-439f-b914-2b3beb40bff9.mp4

**Comment by aarondill** [comment] 2023-04-20 03:35
Shot in the dark here, but the only thing I can think of that would change outside settings is `disable_auto_comment`. Try changing it to false and let me know if that has any change?
```diff
-    disable_auto_comment = true,
+    disable_auto_comment = false,
```

**Comment by aarondill** [comment] 2023-04-20 03:40
Also, this is irrelevant, but, I'd like to point out that you setup `flutter-tools` twice in `basic.lua`:
```lua
require("flutter-tools").setup() -- Line 2
-- ....
require('flutter-tools').setup {} -- Line 13
```

**Comment by MSMazaya** [comment] 2023-04-20 05:35
Hi @aarondill, thanks for answering!

> Also, this is irrelevant, but, I'd like to point out that you setup `flutter-tools` twice in `basic.lua`:

Whoops my bad, changed it

> Shot in the dark here, but the only thing I can think of that would change outside settings is `disable_auto_comment`. Try changing it to false and let me know if that has any change?

No luck, tried it here:

https://user-images.githubusercontent.com/73002733/233267562-ffacd19b-7f63-4495-bea8-f362f8d2b7c7.mp4

**Comment by aarondill** [comment] 2023-04-20 05:38
Well, darn, I'm not sure what the issue is. Perhaps I'll take some time to dig into the source and try to find any conflict sometime later (when it's not 12 in the morning lol).

**Comment by aarondill** [comment] 2023-04-20 05:39
For future reference, which plugin is supplying the relevant code actions?

**Comment by MSMazaya** [comment] 2023-04-20 05:46
> Well, darn, I'm not sure what the issue is. Perhaps I'll take some time to dig into the source and try to find any conflict sometime later (when it's not 12 in the morning lol).

Sure, no worries, thank you for answering :)

> For future reference, which plugin is supplying the relevant code actions?

I use mason to setup my lsp config [here](https://github.com/MSMazaya/.dotfiles/blob/tabnine-issue/nvim/.config/nvim/after/plugin/setup/lsp.lua). The code action keymap is there

```lua
    local nmap = function(keys, func, desc)
        if desc then
            desc = 'LSP: ' .. desc
        end

        vim.keymap.set('n', keys, func, { buffer = bufnr, desc = desc })
    end

    nmap('<leader>ca', vim.lsp.buf.code_action, '[C]ode [A]ction')
```

**Comment by aarondill** [comment] 2023-04-20 14:19
I'm afraid I can't seem to get your dotfiles working on my machine, I'm not particularly familiar with `packer`, so if you could give a quick tutorial (I will be using the new NVIM_APPNAME) on how to get them working, that would be much appreciated

**Comment by aarondill** [comment] 2023-04-20 15:06
Nevermind, I figured it out

**Comment by aarondill** [comment] 2023-04-20 15:08
I figured out the line that's causing issues!
In `lua/tabnine/binary.lua`, line number 10 is this:
```lua
json.encode_empty_table_as_object(true)
```
This is a change that affects the outside scope, and if it's commented, then the code actions will still work. Now I just have to figure out what this does and why it's here.

**Comment by aarondill** [comment] 2023-04-20 15:14
This line changes the vim.json (cjson) implementation from treating an empty table like an array to instead treating it like an (empty) object

**Comment by aarondill** [comment] 2023-04-20 15:17
This really should be fixed with the lsp provider setting this to `false`, but perhaps we can find a way that doesn't modify this setting, to increase the compatibility?

**Comment by aarondill** [comment] 2023-04-20 15:24
actually, the only line where we use `vim.json.encode` (which is the only thing this setting changes) is 155:
```lua
uv.write(self.stdin, json.encode({ request = request, version = api_version }) .. "\n")
```
`api_version` will never be null, or a table, so we just have to ensure that `request` is never an empty table.
`tabnine_binary:request` is called in `completion.lua`, with a table that looks like this: 
```lua
{
Autocomplete = {
			before = before, -- file text - string (never nil?)
			after = after, -- file text - string (never nil?)
			filename = fn.expand("%:t"), -- string (never nil?)
			region_includes_beginning = true, -- This is a constant
			region_includes_end = false, -- also constant
			max_num_results = 1,  -- constant
			correlation_id = state.requests_counter, -- number (never nil?)
		}
}
```
Thusly, this object should never be empty, or contain an empty object. So, this global state change is *currently* having no change and should be removed. 
The only consideration that will have to be made in the future is to always ensure that a value that's expecting an object is either never empty or that the binary accepts an empty array as the empty object.

**Closed** 2023-04-20 19:28 UTC

**Comment by MSMazaya** [comment] 2023-04-20 21:15
Whoa that was quick, thank you for the fix!

**Comment by aarondill** [comment] 2023-04-20 21:17
> Whoa that was quick, thank you for the fix!

Have you tested it? It worked on my machine, would just be nice to know that it works on yours as well

**Comment by MSMazaya** [comment] 2023-04-20 21:28
The LSP is indeed working again :smile: but it seems like my tabnine is always stuck in the `starter` mode.
![image](https://user-images.githubusercontent.com/73002733/233491612-958f450c-e6a6-44a1-a88d-e0dbc19e8733.png)

I'm not sure what causes this, maybe it is just my internet connection problem.

**Comment by aarondill** [comment] 2023-04-20 21:30
thank you for pointing that out. We missed that in the PR

**Comment by aarondill** [comment] 2023-04-20 21:31
@amirbilu what could I add here that would not break the api response but ensure a non empty object? 
```lua
tabnine_binary:request({ State = {} }, function(response)
```

**Comment by amirbilu** [comment] 2023-04-21 04:24
Guys sorry about this. Merging these from my Phone and unable to test every time.
