### ISSUE TITLE
[BUG] Tabnine chat pop errors "e/nvim/plugged/tabnine-nvim/lua/tabnine/chat/binary.lua:82: Expected value but found unexpected end of string at character 65537"

### ISSUE THREAD

**Issue by allan-simon** [codota/tabnine-nvim#151] opened 2024-02-24 11:22 UTC
**Describe the bug**
When using Tabnine chat if I try in the chat window to ask it to generate code 
I will see in my neovim terminal

```
Error executing vim.schedule lua callback: ...re/nvim/plugged/tabnine-nvim/lua/tabnine/chat/binary.lua:82: Expected value but found unexpected end of string at character 65537
stack traceback:
        [C]: in function 'decode'
        ...re/nvim/plugged/tabnine-nvim/lua/tabnine/chat/binary.lua:82: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**To Reproduce**

**Expected behavior**

**Version Info:**

- OS (try `cat /etc/os-release`):  Ubuntu 22.04
- Neovim version (`nvim -v`):   v0.10.0-dev 
- Installed Tabnine Binaries (`ls -A /path/to/plugin/binaries`):   4.111.0
- Active Tabnine Binaries (`cat /path/to/plugin/binaries/.active`):  4.111.0

**Additional context**

**Comment by mumahmud** [comment] 2024-02-29 19:54
I am facing this issue as well. I have noticed this happens anytime chat completes it's generation. This could be after calling `:TabnineFix` or `:TabnineExplain`

**Comment by aarondill** [comment] 2024-03-01 02:52
we could bandage this by giving a nicer warning when json decoding fails (i've been wanting to do this for a while actually), but the actual problem lies in the chat binaries outputting non-json (which is proprietary code, so someone on the TabNine team has to fix it)

**Comment by amirbilu** [comment] 2024-03-15 19:15
@mumahmud  apologies on the late reply.. can you please share a video? i'm unable to reproduce

**Comment by amirbilu** [comment] 2024-03-15 19:17
@allan-simon is this still happening? can you share a video of the issue? is it with `/generate-test-for-code`?

**Comment by amirbilu** [comment] 2024-03-17 19:08
@mumahmud can you please check if you're able to get tabnine chat working now

**Comment by amirbilu** [comment] 2024-03-24 13:33
closing this as fixed. feel free to re-open.

**Closed by amirbilu** 2024-03-24 13:33 UTC

**Comment by jsco2t** [comment] 2024-03-26 21:00
Can we get this re-opened.

I just setup chat *today* and this issue reproduces fairly consistently for me when using `/explain-code`
