### ISSUE TITLE
Lua scoping issues? on load

### ISSUE THREAD

**Issue by camAtGitHub** [codota/tabnine-nvim#2] opened 2022-12-09 14:26 UTC
Hello, 

After speaking with Ezekiel - Im trying to get this too run but failing. 
Happy to help troubleshoot.
So I installed via vim-plug, the `dl_binaries.sh` failed within nvim (lets ignore that for now as I manually ran it successfully). 

Issue #1. `.gitmodules` url should be `http://` not `git://` therefore no reliance on having a github key installed.  

Issue #2. `git submodule sync` and `git submodule update` arent called from the installer / `dl_binaries.sh` and need to be ran manually. 

Issue #3. Main issue: Tabnine not loading.  By default  this is the error I get on load.
```
Error detected while processing /home/cm/.config/nvim/init.vim:
line  173:
E5108: Error executing lua [string ":lua"]:1: module 'tabnine' not found:
        no field package.preload['tabnine']
        no file './tabnine.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/tabnine.lua'
        no file '/usr/local/share/lua/5.1/tabnine.lua'
        no file '/usr/local/share/lua/5.1/tabnine/init.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/tabnine.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/tabnine/init.lua'
        no file './tabnine.so'
        no file '/usr/local/lib/lua/5.1/tabnine.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/tabnine.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

Now I can make it "not error" only by changing my current dir (cwd) to /home/cm/.local/share/nvim/plugged/tabnine-nvim, copying lua/tabnine.lua to "cwd" and changing:
` require('tabnine.utils')` to ` require('lua.tabnine.utils')` in the files:
- tabnine.lua 
- lua/tabnine.lua
- lua/tabnine/binary.lua

Now that stops the nvim errors, but lua line reports 'TabNine Disabled' and tabnine doesnt appear to work. 
Of  note with the above done, if i change the current dir (cwd) to anything else the error comes back. 

Maybe try load the plugin etc from a blank nvim installation and see what errors you get?
Thanks
Cam

**Comment by amirbilu** [comment] 2022-12-09 18:30
Hi @camAtGitHub 

I've just pushed changes to `dl_binaries` & to `.gitmodules` as per your commendations - thanks for that!

Now - I did install `nvim` + `tabnine-nvim` on a fresh docker container (using the updated master branch) and I could get completions immediately.

**However** - I did notice I'm using some new APIs - so it worked only when I've installed the latest `nvim` version.  I will need to add the minimum supported version in the readme later on.

According to the attached stacktrace, `codota/tabnine-nvim` is not in the runtime path, see mine:
![image](https://user-images.githubusercontent.com/7681048/206768308-cf3db1bd-797d-41bb-a193-450300b92caf.png)

- Can you share your `init.nvim `file?
- What is the output of `:set runtimepath?`

Amir

**Comment by camAtGitHub** [comment] 2022-12-10 08:52
HI Amir,

Heres my init.vim 
```
scriptencoding utf-8

set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on

" My show tabs and spaces etc
if has('multi_byte')
    set listchars=tab:>-,trail:˽
    set list
endif

" Enable auto completion menu after pressing TAB.
set wildmenu
set wildchar=<TAB>          "   show possible completions.
set wildmode=list:full
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
" PLUGINS ---------------------------------------------------------------- {{{"{{{

" Auto install vim-plug
" :PlugInstall  - still required - review plugins
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
"  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
  Plug 'https://github.com/rafi/awesome-vim-colorschemes.git'
  Plug 'simnalamburt/vim-mundo'
if version >= 800
    Plug 'codota/tabnine-nvim'
    Plug 'nvim-lualine/lualine.nvim'
endif

" Set the backslash as the leader key.
let mapleader = "\\"

" Press \\ to jump back to the last cursor position.
nnoremap <leader>\ ``

" Press \p to print the current file to the default printer from a Linux operating system.
" View available printers:   lpstat -v
" Set default printer:       lpoptions -d <printer_name>
" <silent> means do not display output.
nnoremap <silent> <leader>p :%w !lp<CR>

" Type jj to exit insert mode quickly.
inoremap jj <Esc>

" Press the space bar to type the : character in command mode.
nnoremap <space> :

" Pressing the letter o will open a new line below the current one.
" Exit insert mode after creating a new line above or below the current line.
nnoremap o o<esc>
nnoremap O O<esc>

" Center the cursor vertically when moving to the next word during a search.
nnoremap n nzz
nnoremap N Nzz

" Yank from cursor to the end of line.
nnoremap Y y$

" You can split a window into sections by typing `:split` or `:vsplit`.
" Display cursorline and cursorcolumn ONLY in active window.
augroup cursor_off
    autocmd!
    autocmd WinLeave * set nocursorline nocursorcolumn
    autocmd WinEnter * set cursorline cursorcolumn
augroup END

call plug#end()
" ------------------------------------------------------------------------ {{{
set mouse=a
" }}}
"
" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored. (ALE)
silent! helptags ALL
set fileencoding=utf-8
set encoding=utf-8
autocmd FileType yaml set indentkeys-=0#
autocmd vimenter * colorscheme OceanicNext

lua << EOF
require('tabnine').setup({
    disable_auto_comment=true,
    accept_keymap="<Tab>",
    debounce_ms = 300,
    suggestion_color = {gui = "#808080", cterm = 244}
})
EOF

lua << EOF
require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
    component_separators = { left = '', right = ''},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {
      statusline = {},
      winbar = {},
    },
    ignore_focus = {},
    always_divide_middle = true,
    globalstatus = false,
    refresh = {
      statusline = 1000,
      tabline = 1000,
      winbar = 1000,
    }
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff', 'diagnostics'},
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  winbar = {},
  inactive_winbar = {},
  extensions = {}
}
EOF

lua << EOF
require('lualine').setup({
    tabline = {
        lualine_a = {},
        lualine_b = {'branch'},
        lualine_c = {'filename'},
        lualine_x = {},
        lualine_y = {},
        lualine_z = {}
    },
    sections = {lualine_c = {'lsp_progress'}, lualine_x = {'tabnine'}}
})
EOF
```
Results of `:echo &rtp`:
```
runtimepath=~/.config/nvim,~/.local/share/nvim/plugged/awesome-vim-colorschemes,~/.local/share/nvim/plugged/vim-mundo,~/.local/share/nvim/plugged/tabnine-nvim,~/.local/share/nvim/plugged/lualine.nvim,/etc/xdg/nvim,~/.local/share/
nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/tmp/.mount_nvim09KFxOlK/usr/share/nvim/runtime,/tmp/.mount_nvim09KFxOlK/usr/share/nvim/runtime/pack/dist/opt/matchit,/tmp/.mount_nvim09KFxOlK/usr/lib/nvim,/usr/share/nvim/s
ite/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.local/share/nvim/plugged/awesome-vim-colorschemes/after,~/.config/nvim/after
```
Results of `:version`:
```
NVIM v0.9.0-dev-490+gf96fb23de
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconv
ersion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURC
E -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/__w/neovim/neovim/.deps/usr/include -I/usr/include -I/__w/neovim/neovim/build/src/nvim/aut
o -I/__w/neovim/neovim/build/include
Compiled by root@497f41b22b70
```
I believe the commits / builds are as recent as 2 days ago. Running via 'appimage'.
I also made sure to clear any old files etc etc and there are no load errors now and can report the installation was error free too.
"Lualine" always reports "Tabnine Disabled" (and still no worky work) 🤣

**Comment by amirbilu** [comment] 2022-12-10 18:23
Just tried your `init.vim` and it works
![image](https://user-images.githubusercontent.com/7681048/206869765-55f3de33-6957-4253-89a0-352e06b08801.png)

**Comment by camAtGitHub** [comment] 2022-12-12 03:37
Im at a loss.
Only difference I can think is the docker environment is causing a difference eg. glibc? or something.
I have tried on a newly installed host with AppImage neovim below are my instructions to reproduce (root user not required).

```
mkdir -p ~/.config/nvim
# copy init.vim to ~/.config/nvim/init.vim #
wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod +x nvim.appimage
./nvim.appimage --appimage-extract
# launches neovim, count to 10, and quit (vim-plug now installed)
./squashfs-root/AppRun 
# launches neovim and installs plugins
 ./squashfs-root/AppRun ~/.config/nvim/init.vim -c :PlugInstall # Exit nvim after PlugInstall completes
# Launch with TabNine now installed...
 ./squashfs-root/AppRun ~/foo.js
# Type some words, press <tab> etc etc nothing happens
# Type more words and more and more and nothing. 
# (Lualine still reports tabnine disabled FYI)
```
 Anyway thats how I'm using is on Redhat 8.7 (glibc 2.28)

**Comment by amirbilu** [comment] 2022-12-22 07:48
Hi @camAtGitHub did you manage to make it work? I wasn't able to reproduce it

**Comment by amirbilu** [comment] 2022-12-23 19:54
@camAtGitHub I'm going to close this for now. 
Feel free to reopen if you think I can assist.

**Closed by amirbilu** 2022-12-23 19:54 UTC

**Comment by joshemorris** [comment] 2023-12-05 00:47
I ran into a very similar issue to this. For me, the resolution was to move the Lua setup code after the plugin installation lines. This seems to be necessary for the Lua paths to get set correctly. Per the vim-plug faq, "Plugins are not activated before plug#end()".

https://github.com/junegunn/vim-plug/wiki/faq#im-getting-cannot-find-color-scheme--does-vim-plug-support-color-schemes
