### ISSUE TITLE
[BUG] Cursor position outside buffer 

### ISSUE THREAD

**Issue by gachikuku** [codota/tabnine-nvim#157] opened 2024-03-14 21:23 UTC
https://github.com/codota/tabnine-nvim/assets/11743804/5dc7abf9-11f4-4be2-98ae-e3d293ee8f00

When I press TAB to complete, the error shown in the video is displayed.

**Version Info:**

- OS: aarch64-apple-darwin
- Neovim version : 
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

- Installed Tabnine Binaries: 4.116.0
- Active Tabnine Binaries: `no matches found`

My tabnine config https://github.com/gachikuku/.dotfiles/blob/main/nvim/.config/nvim/lua/gachikuku/lazy/tabnine.lua

The `dl_binaries.sh` script has been ran manually within the plugin directory `~.local/share/nvim/lazy/tabnine-nvim`
I could not get it to work by simply including this `build = "./dl_binaries.sh"` in my lazyvim config.

**Comment by aarondill** [comment] 2024-03-14 21:46
@amirbilu this is caused by #156
the expression to calculate the new line number should be:
```lua
fn.line(".") + #lines - 2
```
the current line, plus the number of lines to insert, minus one because the api is 0 indexed, minus one because the current line already exists.

**Comment by aarondill** [comment] 2024-03-14 21:48
@gachikuku if you change line 29 in `~/.local/share/nvim/lazy/tabnine-nvim/lua/tabnine/completion.lua `

to this:
```lua
api.nvim_win_set_cursor(0, { fn.line(".") + #lines - 2, fn.col(".") + #lines[#lines] })
```
does it fix the issue?

**Comment by gachikuku** [comment] 2024-03-14 23:28
<img width="1352" alt="image" src="https://github.com/codota/tabnine-nvim/assets/11743804/7e469962-c0c6-42e8-b5be-639cadf25343">


Actually it made it worse.
Now the error occurs on one line and mulitple lines. Before only on mulitple lines.

**Comment by gachikuku** [comment] 2024-03-14 23:42
`api.nvim_win_set_cursor(0, { fn.line("."), fn.col(".") + #lines[#lines] })` 
fixes it. 
Found on #155

**Comment by amirbilu** [comment] 2024-03-15 06:18
Thanks. This is a regression made by a recent PR i merged. Apologies.

**Closed by amirbilu** 2024-03-15 06:18 UTC

**Comment by barrydevp** [comment] 2024-03-15 14:23
@amirbilu I think the difference is in the neovim version. In #155 I'm using v0.10 whereas this issue is in v0.9.5. Perhaps neovim `nvim_win_set_cursor` api has changed its behaviour in the new version. Should we use another approach by using `nvim_feedkeys` as in copilot?
<img width="660" alt="Screen Shot 2024-03-15 at 10 16 04" src="https://github.com/codota/tabnine-nvim/assets/50762788/37b29785-2eff-440e-bac1-57ac4d76f9f6">

**Comment by barrydevp** [comment] 2024-03-15 17:04
@amirbilu I think I found the change on the neovim `nvim_buf_set_lines` API affects this behaviour as in https://github.com/codota/tabnine-nvim/issues/155#issuecomment-2000057812. We could continue on #155.
