### ISSUE TITLE
Error executing vim.schedule lua callback: ...l/share/nvim/plugged/tabnine-nvim/lua/tabnine/status.lua:20: attempt to index local 'response' (a userdata value[BUG]

### ISSUE THREAD

**Issue by allan-simon** [codota/tabnine-nvim#120] opened 2023-09-30 14:07 UTC
**Describe the bug**

Typing text sometimes make the issue above happen
```
Error executing vim.schedule lua callback: ...l/share/nvim/plugged/tabnine-nvim/lua/tabnine/status.lua:20: attempt to index local 'response' (a userdata value)                     
stack traceback:
        ...l/share/nvim/plugged/tabnine-nvim/lua/tabnine/status.lua:20: in function 'callback'
        ...l/share/nvim/plugged/tabnine-nvim/lua/tabnine/binary.lua:89: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
**To Reproduce**

Just typing text and it pops from time to time

**Version Info:**

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Tabnine version: 4.14.0
 - Programming language: [e.g. js, ts, c++]	: `php`

**Comment by aarondill** [comment] 2023-09-30 19:29
This is a duplicate of #119.

**Closed** 2023-10-27 12:25 UTC
