### ISSUE TITLE
[bug] Ghost text stays if you leave insert mode before the completion finishes loading

### ISSUE THREAD

**Issue by luiz00martins** [codota/tabnine-nvim#22] opened 2023-01-27 18:01 UTC
_Note: There's a possibility that you **need** to have a slow internet connection to reliably reproduce this. Unfortunately, I do :,)_

### Description
If tabnine-nvim starts loading a completion during insert mode, and you leave insert mode before the completion finishes loading, the ghost text _still_ appears, and sticks around until you enter insert mode again.

### How to reproduce
1. Enter insert mode
2. Type something that would trigger completion
3. Leave insert mode _before_ the completion finishes loading

### Example
In the video below: 
- I enter insert mode, trigger a completion, _wait for the ghost text to appear_, and leave insert mode. Everything works as expected.
- Then, I enter insert mode, trigger a completion, _and quickly leave insert mode, before the ghost text can appear_. The ghost text still appears (outside of insert mode), and sticks around even as I'm moving in normal mode.
- I then enter insert mode again, and the ghost text properly disappears

https://user-images.githubusercontent.com/43142209/215158570-ac22ec7a-bba3-49d5-813c-f1b2a8235f77.mp4

---

_Note: This might be a duplicate of #17. However, as there aren't many details there, I don't know if this cover his exact issue._

**Comment by amirbilu** [comment] 2023-01-28 19:22
Hi @luiz00martins 
Thanks for submitting this!
I'm aware of this issue - the plugin has indeed naive implementation which assumes latency is low enough to get suggestions render at the proper place.

Not sure if I can get into this in the next couple of weeks. Promise to do my best. I'll leave this open until this is stored.

**Comment by amirbilu** [comment] 2023-01-30 13:47
@luiz00martins can you try for some time (let's say a day) using this https://github.com/codota/tabnine-nvim/pull/24 ?
I wonder if this would help

**Comment by luiz00martins** [comment] 2023-01-30 15:10
A priori, it does. I can't replicate the issue.

I'll use it for a little while, and if I see nothing, I'll close this one :)

**Comment by luiz00martins** [comment] 2023-02-02 22:58
After having used for 3 days, I only saw the problem happening _once_. And even if you asked me to replicate I couldn't, which means that it's probably a different issue which I'm not attuned to (making it more similar to #17).

So, I'm pretty sure that branch solves this issue.

Should I just close this one, or should I wait until the branch gets merged?

**Comment by amirbilu** [comment] 2023-02-03 13:34
@luiz00martins Glad to hear!
Any chance you're giving few days to the latest beta release? it improves the ux significantly!
See details here
https://github.com/codota/tabnine-nvim/issues/26

Appreciate it!

**Comment by luiz00martins** [comment] 2023-02-03 19:23
Yep, will do :smile:

**Comment by amirbilu** [comment] 2023-02-03 19:41
Thanks! Highly appreciated ☺️
https://github.com/codota/tabnine-nvim/tree/beta

**Comment by luiz00martins** [comment] 2023-02-03 20:57
> So, I'm pretty sure that branch solves this issue.

I retract this btw. I just tried again, and I can realiably replicate the issue (in the `response-request` branch):

https://user-images.githubusercontent.com/43142209/216709204-2478259a-77c1-4204-be35-485f72e02581.mp4

**Comment by amirbilu** [comment] 2023-02-04 05:29
Bummer :)
I cannot reproduce this at my machine. I'll see what I can do. 
How do you generally feel about the new experience? (competition stays as you're overlapping it)

**Comment by luiz00martins** [comment] 2023-02-05 03:59
I just came back to my main PC (was using another one while on vacation), and this system is primarily Windows.

I tried to naively convert the `dl_binaries.sh` to powershell, but I'm getting a 403 Forbidden (Access Denied) on the webrequest:
```powershell
# This script downloads the binaries for the most recent version of TabNine.

$version = (Invoke-WebRequest https://update.tabnine.com/bundles/version -UseBasicParsing).Content
$targets = @('i686-pc-windows-gnu', 'x86_64-apple-darwin', 'x86_64-pc-windows-gnu', 'x86_64-unknown-linux-musl', 'aarch64-apple-darwin')
Remove-Item Binaries -Force -Recurse
foreach ($target in $targets) {
    $path = "Binaries/$version/$target"
    New-Item $path -ItemType directory
    Invoke-WebRequest https://update.tabnine.com/bundles/$path/TabNine.zip -OutFile $path/TabNine.zip # <--- On this one
    Expand-Archive $path/TabNine.zip -DestinationPath $path
    Remove-Item $path/TabNine.zip
    & $path/*
}
```

Am I doing something wrong in the request?

**Comment by amirbilu** [comment] 2023-02-05 06:43
@luiz00martins I haven't tested this on Windows.. I'm pretty sure other things won't work :)
You can use `cmp-tabnine` install script https://github.com/tzachar/cmp-tabnine/blob/main/install.ps1

**Comment by amirbilu** [comment] 2023-02-05 08:47
I've just merged this to master. Let me know if still happens you on the master branch. I cannot reproduce this myself for some reason.

**Comment by luiz00martins** [comment] 2023-02-06 04:55
Goofy code. This one downloads the files fine:
```powershell
# This script downloads the binaries for the most recent version of TabNine.

$version = (Invoke-WebRequest https://update.tabnine.com/bundles/version -UseBasicParsing).Content
$platforms = @('i686-pc-windows-gnu', 'x86_64-apple-darwin', 'x86_64-pc-windows-gnu', 'x86_64-unknown-linux-musl', 'aarch64-apple-darwin')
Remove-Item Binaries -Force -Recurse
New-Item Binaries -ItemType directory
foreach ($platform in $platforms) {
    $target = "$version/$platform"
		$path = "Binaries/$target"
		New-Item $path -ItemType directory
		Invoke-WebRequest "https://update.tabnine.com/bundles/$target/TabNine.zip" -OutFile $path/TabNine.zip # <--- On this one
		Expand-Archive $path/TabNine.zip -DestinationPath $path
		Remove-Item $path/TabNine.zip
}
```
I think you're right though, it doesn't seem to work on Windows.

---

> I've just merged this to master. Let me know if still happens you on the master branch. I cannot reproduce this myself for some reason.

I came back to my main PC, which has a way better performance and internet connection, so unfortunately I can't replicate as well either :/

---

> How do you generally feel about the new experience? (competition stays as you're overlapping it)

I'm lovin it :)

**Comment by amirbilu** [comment] 2023-03-13 08:47
Closing this for now. Feel free to reopen if this is still an issue!

**Closed by amirbilu** 2023-03-13 08:47 UTC
